version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    #ports:
      #- "8000:80"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: dbpassword
      WORDPRESS_DB_NAME: db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.wordpress-secure.entrypoints=websecure"
      - "traefik.http.routers.wordpress-secure.rule=Host(`wtactive.com`)"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - proxy

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword
      MYSQL_DATABASE: db
      MYSQL_USER: douser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy

volumes:
  wordpress_data:
  db_data:
networks:
  proxy:
    external: true
